poa_dt <- tibble::tribble(
  ~postcode,   ~district,                                                                   ~suburb,
       3000, "Melbourne",                                                                           "Melbourne",
       3001, "Melbourne",                                                                           "Melbourne",
       3002, "Melbourne",                                                                      "East Melbourne",
       3003, "Melbourne",                                                                      "West Melbourne",
       3004, "Melbourne",                                                             "St Kilda Road Melbourne",
       3005, "Melbourne",                                                                  "World Trade Centre",
       3006, "Melbourne",                                                                           "Southbank",
       3008, "Melbourne",                                                                           "Docklands",
       3010, "Melbourne",                                                             "University Of Melbourne",
       3011, "Melbourne",                                                      "Footscray, Seddon, Seddon West",
       3012, "Melbourne",                          "Brooklyn, Kingsville, Maidstone, Tottenham, West Footscray",
       3013, "Melbourne",                                                         "Yarraville, Yarraville West",
       3015, "Melbourne",                                                "Newport, South Kingsville, Spotswood",
       3016, "Melbourne",                                                                        "Williamstown",
       3018, "Melbourne",                                                                    "Altona, Seaholme",
       3019, "Melbourne",                                                                 "Braybrook, Robinson",
       3020, "Melbourne",                                                                    "Albion, Sunshine",
       3021, "Melbourne",                                            "Albanvale, Kealba, Kings Park, St Albans",
       3022, "Melbourne",                                                              "Ardeer, Deer Park East",
       3023, "Melbourne",                                     "Burnside, Cairnlea, Caroline Springs, Deer Park",
       3024, "Melbourne",                                                        "Mount Cottrell, Wyndham Vale",
       3025, "Melbourne",                                                                        "Altona North",
       3026, "Melbourne",                                                                      "Laverton North",
       3027, "Melbourne",                                                                    "Williams Landing",
       3028, "Melbourne",                                                  "Altona Meadows, Laverton, Seabrook",
       3029, "Melbourne",                                                "Hoppers Crossing, Tarneit, Truganina",
       3030, "Melbourne",                                                      "Derrimut, Point Cook, Werribee",
       3031, "Melbourne",                                                              "Flemington, Kensington",
       3032, "Melbourne",                                 "Ascot Vale, Highpoint City, Maribyrnong, Travancore",
       3033, "Melbourne",                                                                         "East Keilor",
       3034, "Melbourne",                                                                    "Avondale Heights",
       3036, "Melbourne",                                                                "Keilor, Keilor North",
       3037, "Melbourne",                                                         "Delahey, Hillside, Sydenham",
       3038, "Melbourne",                                                         "Keilor Downs, Taylors Lakes",
       3039, "Melbourne",                                                                        "Moonee Ponds",
       3040, "Melbourne",                                                 "Aberfeldie, Essendon, Essendon West",
       3041, "Melbourne",                                      "Essendon North, Strathmore, Strathmore Heights",
       3042, "Melbourne",                                                  "Airport West, Keilor Park, Niddrie",
       3043, "Melbourne",                                              "Gladstone Park, Gowanbrae, Tullamarine",
       3044, "Melbourne",                                                      "Pascoe Vale, Pascoe Vale South",
       3045, "Melbourne",                                                                   "Melbourne Airport",
       3046, "Melbourne",                                                         "Glenroy, Hadfield, Oak Park",
       3047, "Melbourne",                                                        "Broadmeadows, Dallas, Jacana",
       3048, "Melbourne",                                                            "Coolaroo, Meadow Heights",
       3049, "Melbourne",                                                                "Attwood, Westmeadows",
       3050, "Melbourne",                                                            "Royal Melbourne Hospital",
       3051, "Melbourne",                                                        "Hotham Hill, North Melbourne",
       3052, "Melbourne",                                                     "Melbourne University, Parkville",
       3053, "Melbourne",                                                              "Carlton, Carlton South",
       3054, "Melbourne",                                                         "Carlton North, Princes Hill",
       3055, "Melbourne",                                                                      "Brunswick West",
       3056, "Melbourne",                                                                           "Brunswick",
       3057, "Melbourne",                                                                      "Brunswick East",
       3058, "Melbourne",                                          "Coburg, Coburg North, Merlynston, Moreland",
       3059, "Melbourne",                                                                           "Greenvale",
       3060, "Melbourne",                                                                             "Fawkner",
       3061, "Melbourne",                                                                       "Campbellfield",
       3062, "Melbourne",                                                                            "Somerton",
       3063, "Melbourne",                                                           "Oaklands Junction, Yuroke",
       3064, "Melbourne",                         "Craigieburn, Donnybrook, Kalkallo, Mickleham, Roxburgh Park",
       3065, "Melbourne",                                                                             "Fitzroy",
       3066, "Melbourne",                                                                         "Collingwood",
       3067, "Melbourne",                                                                          "Abbotsford",
       3068, "Melbourne",                                                         "Clifton Hill, Fitzroy North",
       3070, "Melbourne",                                                                           "Northcote",
       3071, "Melbourne",                                                                           "Thornbury",
       3072, "Melbourne",                               "Northland Centre, Preston, Preston South, Regent West",
       3073, "Melbourne",                                                                "Reservoir, Keon Park",
       3074, "Melbourne",                                                                          "Thomastown",
       3075, "Melbourne",                                                                               "Lalor",
       3076, "Melbourne",                                                                   "Epping, Epping Dc",
       3078, "Melbourne",                                                               "Alphington, Fairfield",
       3079, "Melbourne",                                                               "Ivanhoe, Ivanhoe East",
       3081, "Melbourne",                                 "Heidelberg Heights, Heidelberg Rgh, Heidelberg West",
       3082, "Melbourne",                                                                           "Mill Park",
       3083, "Melbourne",                                                                 "Bundoora, Kingsbury",
       3084, "Melbourne",                                   "Banyule, Eaglemont, Heidelberg, Rosanna, Viewbank",
       3085, "Melbourne",                                                                  "Macleod, Yallambie",
       3087, "Melbourne",                                                                            "Watsonia",
       3088, "Melbourne",                                             "Briar Hill, Greensborough, Saint Helena",
       3089, "Melbourne",                                                                       "Diamond Creek",
       3090, "Melbourne",                                                                              "Plenty",
       3091, "Melbourne",                                                                           "Yarrambat",
       3093, "Melbourne",                                                                        "Lower Plenty",
       3094, "Melbourne",                                                                         "Montmorency",
       3095, "Melbourne",                                                      "Eltham, Eltham North, Research",
       3096, "Melbourne",                                                                         "Wattle Glen",
       3097, "Melbourne",                                     "Bend Of Islands, Kangaroo Ground, Watsons Creek",
       3099, "Melbourne",                    "Arthurs Creek, Cottles Bridge, Hurstbridge, Nutfield, Strathewen",
       3101, "Melbourne",                                                                                 "Kew",
       3102, "Melbourne",                                                                            "Kew East",
       3103, "Melbourne",                                                                              "Balwyn",
       3104, "Melbourne",                                                                        "Balwyn North",
       3105, "Melbourne",                                                                             "Bulleen",
       3106, "Melbourne",                                                                         "Templestowe",
       3107, "Melbourne",                                                                   "Templestowe Lower",
       3108, "Melbourne",                                                                           "Doncaster",
       3109, "Melbourne",                               "Doncaster East, Doncaster Heights, Tunstall Square Po",
       3110, "Melbourne",                                                                       "Nunawading Bc",
       3111, "Melbourne",                                                                             "Donvale",
       3113, "Melbourne",                                                        "North Warrandyte, Warrandyte",
       3114, "Melbourne",                                                                       "Park Orchards",
       3115, "Melbourne",                                                                          "Wonga Park",
       3116, "Melbourne",                                                                      "Chirnside Park",
       3121, "Melbourne",                                                         "Burnley, Cremorne, Richmond",
       3122, "Melbourne",                                                                            "Hawthorn",
       3123, "Melbourne",                                                                       "Hawthorn East",
       3124, "Melbourne",  "Camberwell, Camberwell North, Camberwell South, Camberwell West, Middle Camberwell",
       3125, "Melbourne",                                                               "Bennettswood, Burwood",
       3126, "Melbourne",                                                         "Camberwell East, Canterbury",
       3127, "Melbourne",                                                           "Mont Albert, Surrey Hills",
       3128, "Melbourne",                                      "Box Hill, Box Hill South, Houston, Wattle Park",
       3129, "Melbourne",                                        "Box Hill North, Kerrimuir, Mont Albert North",
       3130, "Melbourne",                               "Blackburn, Blackburn North, Blackburn South, Laburnum",
       3131, "Melbourne",                                           "Brentford Square, Forest Hill, Nunawading",
       3132, "Melbourne",                                                                  "Mitcham, Rangeview",
       3133, "Melbourne",                                                              "Vermont, Vermont South",
       3134, "Melbourne",                              "Ringwood, Ringwood North, Warrandyte South, Warranwood",
       3135, "Melbourne",                                              "Bedford Road, Heathmont, Ringwood East",
       3136, "Melbourne",                                "Croydon, Croydon Hills, Croydon North, Croydon South",
       3137, "Melbourne",                                                              "Kilsyth, Kilsyth South",
       3138, "Melbourne",                                                                         "Mooroolbark",
       3139, "Melbourne",     "Hoddles Creek, Launching Place, Seville, Wandin North, Woori Yallock, Yellingbo",
       3140, "Melbourne",                                                                            "Lilydale",
       3141, "Melbourne",                                                                         "South Yarra",
       3142, "Melbourne",                                                                   "Hawksburn, Toorak",
       3143, "Melbourne",                                                            "Armadale, Armadale North",
       3144, "Melbourne",                                                                    "Kooyong, Malvern",
       3145, "Melbourne",                                 "Caulfield East, Central Park, Darling, Malvern East",
       3146, "Melbourne",                                                                           "Glen Iris",
       3147, "Melbourne",                                                                  "Ashburton, Ashwood",
       3148, "Melbourne",                                                               "Chadstone, Holmesglen",
       3149, "Melbourne",                                                              "Mount Waverley, Syndal",
       3150, "Melbourne",                                                        "Glen Waverley, Wheelers Hill",
       3151, "Melbourne",                                                       "Burwood East, Burwood Heights",
       3152, "Melbourne",                               "Knox City Centre, Studfield, Wantirna, Wantirna South",
       3153, "Melbourne",                                                          "Bayswater, Bayswater North",
       3154, "Melbourne",                                                                           "The Basin",
       3155, "Melbourne",                                                                             "Boronia",
       3156, "Melbourne", "Ferntree Gully, Lysterfield, Lysterfield South, Mountain Gate, Upper Ferntree Gully",
       3158, "Melbourne",                                                                               "Upwey",
       3159, "Melbourne",                                                                "Menzies Creek, Selby",
       3160, "Melbourne",                                                                    "Belgrave, Tecoma",
       3161, "Melbourne",                                                 "Caulfield Junction, Caulfield North",
       3162, "Melbourne",                                        "Caulfield, Caulfield South, Hopetoun Gardens",
       3163, "Melbourne",                                                  "Carnegie, Glen Huntly, Murrumbeena",
       3164, "Melbourne",                                                                     "Dandenong South",
       3165, "Melbourne",                                                         "Bentleigh East, Coatesville",
       3166, "Melbourne",                                    "Hughesdale, Huntingdale, Oakleigh, Oakleigh East",
       3167, "Melbourne",                                                                      "Oakleigh South",
       3168, "Melbourne",                                                               "Clayton, Notting Hill",
       3169, "Melbourne",                                                             "Clarinda, Clayton South",
       3170, "Melbourne",                                                                            "Mulgrave",
       3171, "Melbourne",                                                         "Sandown Village, Springvale",
       3172, "Melbourne",                                                   "Dingley Village, Springvale South",
       3173, "Melbourne",                                                                         "Keysborough",
       3174, "Melbourne",                                                        "Noble Park, Noble Park North",
       3175, "Melbourne",                              "Bangholme, Dandenong, Dandenong North, Dandenong South",
       3176, "Melbourne",                                                                         "Scoresby Bc",
       3177, "Melbourne",                                                               "Doveton, Eumemmerring",
       3178, "Melbourne",                                                                            "Rowville",
       3179, "Melbourne",                                                                            "Scoresby",
       3180, "Melbourne",                                                                           "Knoxfield",
       3181, "Melbourne",                                                                    "Prahran, Windsor",
       3182, "Melbourne",                                             "St Kilda, St Kilda South, St Kilda West",
       3183, "Melbourne",                                                            "Balaclava, St Kilda East",
       3184, "Melbourne",                                                               "Brighton Road, Elwood",
       3185, "Melbourne",                                                  "Elsternwick, Gardenvale, Ripponlea",
       3186, "Melbourne",                                                                     "Brighton, Dendy",
       3187, "Melbourne",                                                           "Brighton East, North Road",
       3188, "Melbourne",                                                "Hampton, Hampton East, Hampton North",
       3189, "Melbourne",                                                  "Moorabbin, Moorabbin East, Wishart",
       3190, "Melbourne",                                                                             "Highett",
       3191, "Melbourne",                                                                         "Sandringham",
       3192, "Melbourne",                                       "Cheltenham, Cheltenham East, Southland Centre",
       3193, "Melbourne",                                                       "Beaumaris, Black Rock, Cromer",
       3194, "Melbourne",                                                          "Mentone, Moorabbin Airport",
       3195, "Melbourne",             "Aspendale, Aspendale Gardens, Braeside, Mordialloc, Parkdale, Waterways",
       3196, "Melbourne",                                       "Bonbeach, Chelsea, Chelsea Heights, Edithvale",
       3197, "Melbourne",                                                             "Carrum, Patterson Lakes",
       3198, "Melbourne",                                                             "Belvedere Park, Seaford",
       3199, "Melbourne",                                                "Frankston, Frankston South, Karingal",
       3200, "Melbourne",                                                       "Frankston North, Pines Forest",
       3201, "Melbourne",                                                                        "Carrum Downs",
       3202, "Melbourne",                                                                          "Heatherton",
       3204, "Melbourne",                                                         "Bentleigh, Mckinnon, Ormond",
       3205, "Melbourne",                                                 "South Melbourne, South Melbourne Dc",
       3206, "Melbourne",                                                            "Albert Park, Middle Park",
       3207, "Melbourne",                                                         "Garden City, Port Melbourne"
  ) %>%
  data.table::as.data.table(.) %>%
  .[, suburb := tstrsplit(suburb, ","), by = 1:nrow(.)] %>%
  .[, suburb := gsub(" ", "+", suburb)]
